### ISSUE TITLE
Add Console/GUI autostart instructions

### ISSUE THREAD

**Issue by afraprie** [acrobotic/Ai_Samples_RPi#4]
(1) Create autostart.sh in /home/pi/Desktop

FILE [autostart.sh]
# !/bin/bash
# NOTE: Script is called from /etc/rc.local
# This is a comment

echo "AutoStart - Hello World"
# NOTE: '$SHELL' returns control to the user - keeping console open

$SHELL

(2) Add another *.desktop file in '/home/pi/.config/autostart/

FILE [autostartsh.desktop]
[Desktop Entry]
Type=Application
Terminal=false
Exec=lxterminal --command "/home/pi/Desktop/autostart.sh"

**Comment by lucasrangit** [comment]
Thanks! I've incorporated the concept into the wiki at https://github.com/acrobotic/Ai_Demos_RPi/wiki#auto-start-console-program-in-a-gui-terminal . I've simplified it a bit so that they don't need to create that initial script that drops you to a shell. Cool trick but I think it's better if new users simply open a new terminal window. Advanced users such as yourself will know how to return to the shell from a script.
